### ISSUE TITLE
More Config Options

### ISSUE THREAD

**Issue by Dragnier** [Rohzek/SimpleOreGeneration#1]
This mod definitely needs the ability for users to specify new ores from other mods and to adjust spawn weights, spread, vein size, etc.

**Comment by Rohzek** [comment]
Adding configs for the spawn options is easy, and will come for sure, with the next update. But I'm not sure how I would go about supporting ores from other mods. I'm pretty sure I'd have to make a compatibility patch for each mod that's supported somehow.

**Comment by Dragnier** [comment]
Take a look at [MMD Orespawn](https://github.com/MinecraftModDevelopment/OreSpawn). They have configs where you specify what ore to spawn, but I like the veins in your mod. Maybe looking at their code will give you some ideas?

**Comment by CreativeCodeCat** [comment]
Is this feature still going to be coming?

**Comment by Rohzek** [comment]
Yes. Just been dragged down between school and personal issues. Sorry it's taking so long.

**Comment by Rohzek** [comment]
Update uploaded on CurseForge (and the source updated here) for Minecraft version 1.11.2, built on Forge version 13.20.0.2228.
