### ISSUE TITLE
[1.12] Wierd error in my latest.log related to your mod

### ISSUE THREAD

**Issue by Dragnier** [Rohzek/SimpleOreGeneration#10]
[Server thread/WARN]: Simple Ore Generation loaded a new chunk (-5, 3  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

This happens constantly. Also, I reloaded a world and all of the natural spawn Quark Basalt blocks in the chunk I was in had been changed to Quark Basalt Walls... due to the above error; I am thinking it may be related to your mod.

**Comment by Rohzek** [comment]
There is no way that my mod could have touched Quark's blocks. As of now, Forestry, IndustrailCraft 2, and Immersive Engineering (as of 3.5.0 for 1.11.2) are the only mods my mod does anything with.

As for the warning, it means that upon loading a new chunk, sometimes chunks near it get force-loaded too. I've looked pretty hard for proper fix, and the the only thing I really found is that even [vanilla Minecraft has this problem](https://github.com/MinecraftForge/MinecraftForge/blob/4fbc84773650580008295a234302fc5618af5fcb/patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch#L323), but forge mutes the report for it.
