### ISSUE TITLE
Surface Ores require diamond pickaxe

### ISSUE THREAD

**Issue by sandalle** [Rohzek/SimpleOreGeneration#11]
I'm unsure when this happened, but new worlds (SSP and SMP) I've been creating with Simple Ore Generation have this problem where all Surface Ores (e.g. Tin and Uranium, but not vanilla ores like Iron) require a Diamond tool or better to mine. Other mods (e.g. LibVulpes or Thermal Expansion) require the regular level of mining. I haven't gotten to The End nor The Nether on the new worlds to check.

I cannot find a config option for this, and I thought it was caused after adding CoFH and Thermal* mods, but even removing them doesn't fix it (that's also when I made a new world).

If I let Thermal Expansion or others generate some of the surface ores (e.g. CoFH), then they have the normal mining level.

I tried rolling back to Simple Ore Generation 3.3.0, but couldn't get it to even generate Tin and Copper ores (I don't have Forestry installed, but do have other mods which use Tin and Copper; they are disabled for making their own ores).

Forge: 1.11.2-13.20.0.2315
Simple Ore Generation: 3.4.6 mc 1.11.2

Mod Pack: [NST Unofficial - Exploration](https://minecraft.curseforge.com/projects/nst-unofficial-exploration)

**Comment by Rohzek** [comment]
Very strange. While maybe not the level intended for other mods, the current default mining level for my ores is actually set to 2 (you can see [here](https://github.com/Rohzek/SimpleOreGeneration/blob/master/1.11.2/main/java/com/gmail/rohzek/blocks/GenericBlock.java#L24) ) which is Iron level...

No clue why you're requiring Diamond. :o

**Comment by sandalle** [comment]
Me either, and I don't know how to track it down. :/ As a test I switched surface and vanilla oregen to Thermal Foundation and Tin and Copper are now Iron level, while Silver and Lead are Diamond level (for ores generated by Thermal Foundation). Each test I created a new world, so nothing from the old worlds should have affected my tests. If you cannot reproduce it, this may just be a side effect of the mods I'm using or some config changes somewhere, though I have Simple Ore Gen handling almost all of my ore gen (Nuclear Craft and Embers have a little of their own oregen still going).

Using Creative Mode, I spawned in a Copper Ore from Embers, Industrial Craft 2 (experimental), Nuclear Craft, Thermal Foundation, and Simple Ore Generation: All of them _except_ Simple Ore Generation Copper Ore requires an iron mining level pickaxe, while Simple Ore Generation Copper Ore requires a diamond mining level pickaxe. This is without using the worldgen code, I just placed the ore blocks after giving myself some via Just Enough Items Cheat mode.

Then, just to make sure The One Probe isn't playing some weird games with the display, I tried mining them with a vanilla Stone pickaxe, and could mine the ores _except_ Simple Ore Gens. When I tried a vanilla Iron pickaxe, I was able to successfully mine the Simple Ore Gen Copper Ore, and did _not_ need a Diamond-level pickaxe, though The One Probe stated it was diamond-level.

So may be a display or calculation issue with The One Probe?

**Comment by Rohzek** [comment]
Sounds to me like you need to submit a bug report to The One Probe?

Waila correctly reports a mining level of 2, and shows green for an Iron Pick, for all of the ores.

![Waila: Bare Handed](http://i.imgur.com/xFChWTI.png)
![Waila: Iron Pick](http://i.imgur.com/xFChWTI.png)

Whereas The One Probe seems to report mining level 2 as Diamond, while still saying it's mine-able when holding the Iron Pick

![The One Probe: Bare Handed](http://i.imgur.com/LEUPkiQ.png)
![The One Probe: Iron Pick](http://i.imgur.com/OYcMhuV.png)

**Comment by sandalle** [comment]
Yeah, I was just about to say I'll open a bug report with The One Probe when I get back tonight. ;) Other mod ores are also reporting one mining level higher than defined, but the correct tool works fine mining them, sorry for the noise. I was thrown off as the other ores showed working with my stone pickaxe, but not the Simple Ore Gen ores. I didn't realize the Simple Ore Gen Tin/Copper were Iron while IC2 and others treat them as Stone.
