### ISSUE TITLE
[Suggestion / Request] Overworld and End Quartz Ore?

### ISSUE THREAD

**Issue by TDarkShadow** [Rohzek/SimpleOreGeneration#13]
Could you create an option to have Overworld and End Quartz Ore?
I looked around and most people's reason whom wouldn't have non-Nether Quartz was that it would have made the Nether kinda unnecessary to progress in.
However with this mod makes the Nether (and the End) great for double or triple ore processing.

**Comment by Rohzek** [comment]
Added in 3.5.1 mc 1.11.2 & 4.0.6 mc 1.12

**Comment by TDarkShadow** [comment]
Thank you very much!
