### ISSUE TITLE
[Bug][1.11.2] Smelting Nether / End Lapis Ore returns Ink Sacs

### ISSUE THREAD

**Issue by TDarkShadow** [Rohzek/SimpleOreGeneration#14]
Running Minecraft 1.11.2
Forge: forge-13.20.1.2393
File: SimpleOreGeneration-3.5.0 mc 1.11.2.jar

Nether and End Lapis Ores returns Ink Sacs when you smelt them.

**Comment by Rohzek** [comment]
Fixed in 3.5.1 mc 1.11.2 & 4.0.6 mc 1.12
