### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by BSKCorp** [Rohzek/SimpleOreGeneration#15]
Crash on startup
Forge 1.11.2 -13.20.1.2414
Simple Ore Generation 3.5.2 -1.11.2

[crash-2017-07-16_15.09.19-client.txt](https://github.com/Rohzek/SimpleOreGeneration/files/1151327/crash-2017-07-16_15.09.19-client.txt)

**Comment by Rohzek** [comment]
If updated did you delete OreGen.json before launching?

**Comment by BSKCorp** [comment]
No I did not, coming back from a long vacation and have just been updating. Will do that now.

**Comment by BSKCorp** [comment]
Got busy with lil ones, I just deleted the whole config folder and boom worked fine. I'm a real smart person ya know lol should read up more next time. Thank you and sorry for the inconvenience.

**Comment by Rohzek** [comment]
No problem.
