### ISSUE TITLE
[1.12] Quartz not recognized by Applied Energistics fork Applied Llamagistics recipe

### ISSUE THREAD

**Issue by dimensionsintime** [Rohzek/SimpleOreGeneration#16]
I'm using Simple Ore Gen 4.0.7mc1.12 and the fork of Applied Energistics ([Applied Llamagistics by Thiakil](https://minecraft.curseforge.com/projects/applied-llamagistics)) 1.12 beta 1. My forge version is 14.21.1.2419. In AE2 you create a "Fluix" crystal by throwing 1 redstone, 1 nether quartz and 1 charged certus crystal into a water source block for a couple seconds and out pops the fluix crystal. Except it isn't working. I'm not sure which mod is at fault, so I am leaving a message for both. The quartz seems to work everywhere else but in AE2 (or, rather AL2). Thanks for your help.

**Comment by Rohzek** [comment]
AE2 most likely isn't registering their recipes to use the OreDictionary entry for gemQuartz, but specifically calling only certus quartz/nether quartz.
If they provide a specific OreDict entry, I'll add it, but it's probably on their end.

**Comment by dimensionsintime** [comment]
Yes, thiakil's reply indicates that the recipe is looking for vanilla quartz. Thanks!
