### ISSUE TITLE
no bronze ingot or alloy recipe

### ISSUE THREAD

**Issue by Konlii** [Rohzek/SimpleOreGeneration#17]
I am using this mod to generate the ores for Tinker's Construct and Immersive Engineering.  Unfortunately, even though copper and tin are both present, there is no way to actually create bronze.

**Comment by Rohzek** [comment]
With the most recent version, I'm unable to produce any problems with creating bronze with either Immersive Engineering:
![Immersive Engineering](http://i.imgur.com/nq7eMWY.png)

Or with Tinker's Construct:
![Tinker's Construct](http://i.imgur.com/MkFwIR8.png)

Do you have the latest version?
If so do you have any mods like UniDict that might be causing an issue?

**Comment by Konlii** [comment]
Sorry, I forgot to give my version numbers.

forge-1.12-14.21.1.2424
SimpleOreGeneration-4.0.7 mc 1.12
ImmersiveEngineering-0.12-69
Mantle-1.12-1.3.0.15
TConstruct-1.12-2.7.1.9

![2017-07-26_09 16 16](https://user-images.githubusercontent.com/11935163/28625909-30fe50ec-71e3-11e7-8da8-338a5a92604c.png)

![2017-07-26_09 18 54](https://user-images.githubusercontent.com/11935163/28626015-861782c4-71e3-11e7-92fd-f39f191cd272.png)

**Comment by Rohzek** [comment]
Upon closer inspection, I was actually being slow, and I actually do see the problem. 

My mod doesn't have a bronze ingot (as I was more interested in replacing ores used by other mods, not just substituting and providing all metals and alloys and such) and Immersive Engineering, as well as Tinker's Construct don't have their own bronze ingot, it seems. My Bronze was coming from Forestry when testing it (as Forestry is in my build path from supporting it).

I guess I can add in missing ingots and blocks, however, if you'd like.
