### ISSUE TITLE
Simple Dimensions Intergration

### ISSUE THREAD

**Issue by CreativeCodeCat** [Rohzek/SimpleOreGeneration#2]
would be nice to be able to generate ore in dimensions made using [Simple Dimensions](https://minecraft.curseforge.com/projects/simple-dimensions) mod

**Comment by Rohzek** [comment]
I'll see what I can do.

**Comment by Rohzek** [comment]
Update 3.2.0 for Minecraft 1.11.2 adds support for custom dimensions, specifically ones that spawn based on Stone (like the overworld). This should cover most dimensions from Simple Dimensions, as well as other Dimension mods.

If this functionality isn't enough, let me know.
