### ISSUE TITLE
Integrate ores from other mods too

### ISSUE THREAD

**Issue by TekuSP** [Rohzek/SimpleOreGeneration#20]
Recommendation for integrating few more ores into this mod, so there are not two coppers for example.
I would recommend remove generation of these mods:
Forestry
Immersive Engineering
Tech Reborn
Thermal Foundation

and make them use your ingots and your ores and your nuggets.
It will help a lot generation and players.

SimpleOreGeneration 1.12-4.0.7
```
[21:50:07] [main/INFO] [FML]: Forge Mod Loader version 14.21.1.2420 for Minecraft 1.12 loading
[21:50:07] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_141, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_141
```

**Comment by Rohzek** [comment]
I already **do** have Forestry and Immersive Engineering support (although when the last update came out, Immersive Engineering wasn't updated to 1.12 and I had to remove the code temporarily. Will re-add soon), and my ingots should work in their recipes, unless they changed something in their 1.12 versions.

I will take the other two suggestions under advisement for the next two mods to be supported.
