### ISSUE TITLE
Option to replace already generated ores with StoneBlock, after turning them off in the config

### ISSUE THREAD

**Issue by Boymann** [Rohzek/SimpleOreGeneration#21]
Considering your mod generates a lot of ores (a lot of which might not be needed), would it be possible to get an option to remove (replace with stone) the ores that have been turned off in the config? 

Ores already turned off have no use anymore either and might just be world clutter after that point in old chunks.
Just an idea from my own experience, testing on my server was very explorative and less of a mining experience up until now, and we just realized that we don't really need half of the ores generated by this mod. 

Might be useful for someone else too!

**Comment by Rohzek** [comment]
I'm not quite sure how to handle retrogen. Or how that would work if say... someone was using an ore for decoration for some reason. Would definitely cause lag spikes, too, if it has to search through every ore in a chunk multiple times looking for ones that should be gone. Would probably be better to use a test world to determine if an ore was needed before playing with it.

I'm more interested in knowing what ores you've decided you don't need? If it's a truly useless ore, (like copper generating when you have no mods that use it) that's a pretty big bug. If it's just another copper when other mods have it too, which ones? I'll try to add support. Part of what I'm trying to do is unify ores, too.

**Comment by Boymann** [comment]
Well, I was using an old version so the ores are not smeltable (will update soon to fix that) and there is A LOT of everything compared to how much we would prefer, and I mainly got the mod for the nether ores, but mostly it was bauxite, nickel, silver, tin and copper. And we got dupes because I forgot about unified items, which also generated ores.

**Comment by Rohzek** [comment]
Okay. 

It seems Unified Items is more or less a direct competitor as far as ore generation is concerned, so I can't really just add support for it. However if you want to keep it and mine together, you can turn off mine's surface generation (You'd, however, have to start a new world to get rid of the existing ore, or remove my mod and load the world, and then put it back which will cause world holes, or use CoFH Core's clearblocks command to remove them manually). If you're not too attached to Unified Items, UniDict does close to the same thing, but with no ore generation.

**Comment by Boymann** [comment]
Oh boy, did I fuck up on the oregeneration. I'm using your mod for nether ores now(could use for both overworld and nether), unified items for overworld gen, and also unidict in library mode currently. Could've done all with your mod probably. Sadly starting a new world is not an option anymore, but I'll keep on tweaking the configs as we go on. (Really should've started with a testworld, but grew quite impatient.)
