### ISSUE TITLE
NPE during startup after modifying OreGen.json

### ISSUE THREAD

**Issue by Zeevian** [Rohzek/SimpleOreGeneration#22]
I modified my OreGen.json to have more of a balanced feel personally.  I thought I was weird that the values I changed the first time reverted back to normal.  The modified ores the second time starting causing the NPE crash during load.

[crash-2018-01-18_12.53.02-client.txt](https://github.com/Rohzek/SimpleOreGeneration/files/1643924/crash-2018-01-18_12.53.02-client.txt)

[OreGen.txt](https://github.com/Rohzek/SimpleOreGeneration/files/1643933/OreGen.txt)

Edit: I should add in that I have removed all of the other mods I had loaded and regened all the configs from scratch.

Forge Version 1.12.2-14.23.1.2590 (Most Recent)
SimpleOreGen 4.1.3

**Comment by Rohzek** [comment]
Line 875, under endRubyOre, you've left out a comma at the end of the "maxY" entry, and so the json doesn't compile correctly - which means it can't read it and throws a NPE.

![Text Comparison](https://i.imgur.com/u9tPZhW.png)

**Comment by Zeevian** [comment]
I'm an idiot, sorry @Rohzek.  I didn't even think to check that.  I use notepad+ and usually double click to change values.  Thank you for pointing my stupidness.
