### ISSUE TITLE
Remove TF Compatibility.

### ISSUE THREAD

**Issue by KingLemming** [Rohzek/SimpleOreGeneration#23]
Posting this as a heads up. What you are doing with CoFH world files is essentially malware.

I'm putting this here as a request to just remove TF compat from your mod. Otherwise, I'll remove compatibility on my end and throw an exception if I see this mod in the load order. Because I do not appreciate having my mods attacked.

To be clear, you need to not be renaming or deleting ANYTHING in the CoFH world folder. You need to leave it up to pack makers to properly configure things and if they get extra world gen because they didn't, too bad. What you are doing right now though is fully unacceptable.

**Comment by CTH999** [comment]
Yikes, I can't belive someone would do this. Are you still doing @Rohzek? Because if you are, you should stop. And if you aren't, then continue not doing it!
