### ISSUE TITLE
[Suggestion] Make a config for biomes

### ISSUE THREAD

**Issue by Alessandro404** [Rohzek/SimpleOreGeneration#25]
As for now, only the emerald ores are configurable per biome. In a map paking prospective, it could be useful to be able to limit the spawn for every ore.

**Comment by Rohzek** [comment]
A per-ore-biome-selection willl be included in the next update (4.2.2/3.7.2/2.3.1 for 1.12.2/1.11.2/1.10.2 respectively); configurable by editing the list of biomes in the oregen.json file.
