### ISSUE TITLE
Mekanism crash

### ISSUE THREAD

**Issue by specklogan** [Rohzek/SimpleOreGeneration#35]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-134-universal.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  Techguns Core (techguns-1.12.2-2.0.1.2_1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 4/9/19 10:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Simple Ore Generation (simpleoregen)
Caused by: java.lang.NoClassDefFoundError: mekanism/common/config/MekanismConfig$general
	at com.gmail.rohzek.compatibility.MKCompat.fixConfig(MKCompat.java:22)
	at com.gmail.rohzek.compatibility.MKCompat.load(MKCompat.java:13)
	at com.gmail.rohzek.compatibility.CheckForMods.checkForMK(CheckForMods.java:94)
	at com.gmail.rohzek.main.Main.PostLoad(Main.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mekanism.common.config.MekanismConfig$general
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1286568880 bytes (1226 MB) / 4362076160 bytes (4160 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2814 102 mods loaded, 102 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version                  | Source                                             | Signature                                |
	|:----- |:---------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft              | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJ | mcp                    | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJ | FML                    | 8.0.99.99                | forge-1.12.2-14.23.5.2814.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                  | 14.23.5.2814             | forge-1.12.2-14.23.5.2814.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | advancedrocketrycore   | 1                        | minecraft.jar                                      | None                                     |
	| LCHIJ | ivtoolkit              | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
	| LCHIJ | techguns_core          | 1.12.2-1.0               | minecraft.jar                                      | None                                     |
	| LCHIJ | actuallyadditions      | 1.12.2-r146              | ActuallyAdditions-1.12.2-r146.jar                  | None                                     |
	| LCHIJ | redstoneflux           | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal (1).jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJ | cofhcore               | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar             | None                                     |
	| LCHIJ | libvulpes              | 0.4.0.-52                | LibVulpes-1.12.2-0.4.0-52-universal.jar            | None                                     |
	| LCHIJ | advancedrocketry       | 1.5.0.-134               | AdvancedRocketry-1.12.2-1.5.0-134-universal.jar    | None                                     |
	| LCHIJ | bdlib                  | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2 (1).jar                   | None                                     |
	| LCHIJ | betterbuilderswands    | 0.13.1                   | BetterBuildersWands-1.12.2-0.13.1.269+13450ff.jar  | None                                     |
	| LCHIJ | blockcraftery          | 1.12.2-1.2.0             | blockcraftery-1.12.2-1.2.0.jar                     | None                                     |
	| LCHIJ | bookshelf              | 2.3.570                  | Bookshelf-1.12.2-2.3.570.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJ | forgelin               | 1.8.2                    | Forgelin-1.8.2.jar                                 | None                                     |
	| LCHIJ | bountiful              | 2.2.0                    | Bountiful-2.2.0.jar                                | None                                     |
	| LCHIJ | buildcraftlib          | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LCHIJ | buildcraftcore         | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LCHIJ | buildcraftbuilders     | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LCHIJ | buildcrafttransport    | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LCHIJ | buildcraftsilicon      | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LCHIJ | buildcraftcompat       | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LCHIJ | buildcraftenergy       | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LCHIJ | buildcraftfactory      | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LCHIJ | buildcraftrobotics     | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LCHIJ | shadowmc               | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                            | None                                     |
	| LCHIJ | clipboard              | @VERSION@                | Clipboard-1.12-1.3.0.jar                           | None                                     |
	| LCHIJ | codechickenlib         | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal (1).jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | cofhworld              | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal (1).jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJ | mantle                 | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                           | None                                     |
	| LCHIJ | jei                    | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCHIJ | tconstruct             | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                   | None                                     |
	| LCHIJ | conarm                 | 1.2.3                    | conarm-1.12.2-1.2.3.jar                            | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJ | extendedrenderer       | v1.0                     | coroutil-1.12.1-1.2.31.jar                         | None                                     |
	| LCHIJ | coroutil               | 1.12.1-1.2.31            | coroutil-1.12.1-1.2.31.jar                         | None                                     |
	| LCHIJ | configmod              | v1.0                     | coroutil-1.12.1-1.2.31.jar                         | None                                     |
	| LCHIJ | logicaldrops           | 1.12.2-14.23.4.2764      | EM3R50N-LogicalCraft-1.12.2-14.23.4.2764.jar       | None                                     |
	| LCHIJ | enderstorage           | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | exnihilocreatio        | 1.12.2-0.3.9             | exnihilocreatio-1.12.2-0.3.9.jar                   | None                                     |
	| LCHIJ | excompressum           | 3.0.26                   | ExCompressum_1.12.2-3.0.26 (1).jar                 | None                                     |
	| LCHIJ | farseek                | 2.3.1                    | Farseek-1.12-2.3.1.jar                             | None                                     |
	| LCHIJ | cfm                    | 6.2.0                    | furniture-6.2.0-1.12.2 (1).jar                     | None                                     |
	| LCHIJ | thermalfoundation      | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJ | advgenerators          | 0.9.20.12                | generators-0.9.20.12-mc1.12.2 (1).jar              | None                                     |
	| LCHIJ | gravestone             | 1.10.2                   | gravestone-1.10.2.jar                              | None                                     |
	| LCHIJ | harvestables           | 1.2                      | harvestables-1.2.1.jar                             | None                                     |
	| LCHIJ | waila                  | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJ | mts                    | 13.1.0                   | Immersive+Vehicles-1.12.2-13.1.0.jar               | None                                     |
	| LCHIJ | railcraft              | 12.0.0                   | railcraft-12.0.0.jar                               | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJ | immersiveengineering   | 0.12-89                  | ImmersiveEngineering-0.12-89 (1).jar               | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJ | immersivepetroleum     | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9 (2).jar            | None                                     |
	| LCHIJ | immersivetech          | 1.3.10                   | immersivetech-1.12-1.3.10 (1).jar                  | None                                     |
	| LCHIJ | inventorytweaks        | 1.64+dev.146.2180b27     | InventoryTweaks-1.64+dev.146.jar                   | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJ | ironbackpacks          | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| LCHIJ | ironchest              | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar                    | None                                     |
	| LCHIJ | mtsseagullmilitarypack | 1.4.0                    | IV+Seagull's+military+pack+1.4.3.jar               | None                                     |
	| LCHIJ | jaopca                 | 1.12.2-2.2.8.90          | JAOPCA-1.12.2-2.2.8.90.jar                         | None                                     |
	| LCHIJ | oredictinit            | 1.12.2-2.2.1.68          | JAOPCA-1.12.2-2.2.8.90.jar                         | None                                     |
	| LCHIJ | journeymap             | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                        | None                                     |
	| LCHIJ | letsencryptcraft       | @VERSION@                | letsencryptcraft-1.10.2-1.2.0.jar                  | None                                     |
	| LCHIJ | malisiscore            | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
	| LCHIJ | malisisdoors           | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0 (1).jar                  | None                                     |
	| LCHIJ | mekanism               | 1.12.2-9.6.4.356         | Mekanism-1.12.2-9.6.4.356.jar                      | None                                     |
	| LCHIJ | mekanismgenerators     | 1.12.2-9.6.4.356         | MekanismGenerators-1.12.2-9.6.4.356.jar            | None                                     |
	| LCHIJ | mobrecipes             | 1.0.0                    | MobRecipes-1.12.2-1.0.2.jar                        | None                                     |
	| LCHIJ | modroadworksreborn     | 0.0.3                    | modroadworksreborn-0.0.3.jar                       | None                                     |
	| LCHIJ | mtsofficialpack        | 9.0.0                    | MTS_Official_Pack_V09.jar                          | None                                     |
	| LCHIJ | naturescompass         | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                    | None                                     |
	| LCHIJ | thermalexpansion       | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJ | netherfoundation       | 1.2.0                    | NetherFoundation-1.12.2-1.2.0-universal.jar        | None                                     |
	| LCHIJ | recipehandler          | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
	| LCHIJ | orecontrol             | 0.4.0                    | orecontrol-1.12.0-0.4.0.jar                        | None                                     |
	| LCHIJ | oreexcavation          | 1.4.137                  | OreExcavation-1.4.137.jar                          | None                                     |
	| LCHIJ | shetiphiancore         | 3.5.9                    | shetiphiancore-1.12.0-3.5.9.jar                    | None                                     |
	| LCHIJ | platforms              | 1.4.6                    | platforms-1.12.0-1.4.6.jar                         | None                                     |
	| LCHIJ | poweradapters          | 1.0.9                    | PowerAdapters-1.12.2-1.0.9 (2).jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJ | realdrops              | 1.2.14                   | RealisticItemDrops-1.2.14.jar                      | None                                     |
	| LCHIJ | reccomplex             | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                       | None                                     |
	| LCHIJ | additionalstructures   | 2.2.2                    | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar   | None                                     |
	| LCHIJ | simplecorn             | 2.4.1                    | SimpleCorn1.12-1.12-2.4.1.jar                      | None                                     |
	| LCHIE | simpleoregen           | 4.3.2                    | SimpleOreGeneration-4.3.2+mc+1.12.2 (2).jar        | None                                     |
	| LCHI  | thermaldynamics        | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHI  | simplyjetpacks         | 2.2.11.64                | SimplyJetpacks2-1.12.2-2.2.11.64.jar               | None                                     |
	| LCHI  | streams                | 0.4.4                    | Streams-1.12-0.4.4.jar                             | None                                     |
	| LCHI  | techguns               | 2.0.1.2                  | techguns-1.12.2-2.0.1.2_1.jar                      | None                                     |
	| LCHI  | thermalsolars          | 1.12.2 V1.9.4            | thermalsolars-1.12.2-1.9.4.jar                     | None                                     |
	| LCHI  | thutcore               | 5.19.9                   | thutcore-1.12.2-5.19.9.jar                         | None                                     |
	| LCHI  | thutcore_compat        | 1.0                      | thutcore-1.12.2-5.19.9.jar                         | None                                     |
	| LCHI  | thuttech               | 6.1.5                    | thuttech-1.12.2-6.1.5.jar                          | None                                     |
	| LCHI  | tcomplement            | ${version}               | TinkersComplement-1.12.2-0.3.1.jar                 | None                                     |
	| LCHI  | tinkertoolleveling     | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCHI  | tp                     | 3.2.32                   | tinyprogressions-1.12.2-3.3.32-Release.jar         | None                                     |
	| LCHI  | worleycaves            | 1.3.0                    | worleycaves-1.3.0.jar                              | None                                     |
	| LCHI  | structurize            | 1.12.2-0.10.63-ALPHA     | structurize-1.12.2-0.10.63-ALPHA.jar               | None                                     |
	| LCHI  | minecolonies           | 1.12.2-0.10.202-RELEASE  | minecolonies-1.12.2-0.10.202-RELEASE-universal.jar | None                                     |
	| LCHI  | orelib                 | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHI  | terrarium              | 1.0.1                    | terrarium-1.0.1.jar                                | None                                     |
	| LCHI  | earth                  | 1.0.0                    | terrarium-1.0.1.jar                                | None                                     |
	| LCHI  | mysticallib            | 1.12.2-1.1.1             | mysticallib-1.12.2-1.1.1.jar                       | None                                     |
	| LCHI  | wrapup                 | 1.12-1.1.3               | WrapUp-1.12-1.1.3.jar                              | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  farseek.core.FarseekClassTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-134-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
Techguns Core (techguns-1.12.2-2.0.1.2_1.jar)
  techguns.core.TechgunsASMTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ExNihiloPlugin (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (34) from ActuallyAdditions-1.12.2-r146.jar
		* buildcraftapi_blocks (1.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_boards (2.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_core (2.2) from buildcraft-all-7.99.23.jar
		* buildcraftapi_crops (1.1) from buildcraft-all-7.99.23.jar
		* buildcraftapi_enums (1.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_events (2.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_facades (1.1) from buildcraft-all-7.99.23.jar
		* buildcraftapi_filler (5.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_fuels (2.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_gates (4.1) from buildcraft-all-7.99.23.jar
		* buildcraftapi_items (1.1) from buildcraft-all-7.99.23.jar
		* buildcraftapi_library (2.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_lists (1.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_power (1.3) from buildcraft-all-7.99.23.jar
		* buildcraftapi_recipes (3.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_robotics (3.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_statements (1.1) from buildcraft-all-7.99.23.jar
		* buildcraftapi_tiles (1.2) from buildcraft-all-7.99.23.jar
		* buildcraftapi_tools (1.0) from buildcraft-all-7.99.23.jar
		* buildcraftapi_transport (5.0) from buildcraft-all-7.99.23.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.2.25-universal.jar
		* CoroAI|dynamicdifficulty (1.0) from coroutil-1.12.1-1.2.31.jar
		* ExCompressum|API (1.0) from ExCompressum_1.12.2-3.0.26 (1).jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-89 (1).jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-89 (1).jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.4.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.4.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.268.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.6.4.356.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.6.4.356.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.6.4.356.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.6.4.356.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.6.4.356.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.6.4.356.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.6.4.356.jar
		* railcraft:api_carts (3.0.0) from railcraft-12.0.0.jar
		* railcraft:api_charge (4.0.0) from railcraft-12.0.0.jar
		* railcraft:api_core (3.2.0) from railcraft-12.0.0.jar
		* railcraft:api_crafting (4.0.0) from railcraft-12.0.0.jar
		* railcraft:api_events (2.0.0) from railcraft-12.0.0.jar
		* railcraft:api_fuel (2.0.0) from railcraft-12.0.0.jar
		* railcraft:api_helpers (2.0.0) from railcraft-12.0.0.jar
		* railcraft:api_items (2.4.0) from railcraft-12.0.0.jar
		* railcraft:api_signals (4.0.0) from railcraft-12.0.0.jar
		* railcraft:api_tracks (5.1.1) from railcraft-12.0.0.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal (1).jar
		* Thaumcraft|API (6.0.2) from railcraft-12.0.0.jar
		* thut|API (1.0.0) from thutcore-1.12.2-5.19.9.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar

**Comment by specklogan** [comment]
Is there anything I can do for this to work?

**Comment by Rohzek** [comment]
Update going up now.
