### ISSUE TITLE
No IC2C support.

### ISSUE THREAD

**Issue by SlayerTheChikken** [Rohzek/SimpleOreGeneration#36]
Hello, I just wanted to let you know this mod does not work with Industrial Craft 2 Classic, it just crashes. I would love to have this mod in my modpack Tekxit 3 but IC2C support is needed, it would really simplify controlling ore generation and would allow me to remove Nether Ores and replace it with this.

Here is the crash log if needed: https://paste.dimdev.org/tijixelagu.mccrash

**Comment by SlayerTheChikken** [comment]
You self assigned this pretty fast o: Should I wait for a few days to release my modpack update? or it will be more than a week? Let me know, either is oki doki

**Comment by Rohzek** [comment]
> or it will be more than a week

When I get out of class today, I'll be out for a week, for Spring Break, so I should have time to look at it today or tomorrow.

**Comment by Rohzek** [comment]
@Slayer5934 Should be working now. If not, let me know. I'll wait to hear from you before I close the issue.
