### ISSUE TITLE
(EDITED BY ROHZEK) NullPointerException crash

### ISSUE THREAD

**Issue by sandalle** [Rohzek/SimpleOreGeneration#4]
After updating to Simple Ore Generation 3.4.0 mc1.11.2, I get this crash both on my client and server running Forge Mod Loader 1.11.2-13.20.0.2296.

Crash report: [crash-2017-05-08_10.31.05-client.txt](https://github.com/Rohzek/SimpleOreGeneration/files/984375/crash-2017-05-08_10.31.05-client.txt)

**Comment by sandalle** [comment]
I see that you added IC2 support, which may be pertinent as I have Industrial Craft 2 (IC2) Experimental (not Classic) 2.7.12-ex111 installed.

**Comment by Rohzek** [comment]
Have you updated from a previous version?

**Comment by sandalle** [comment]
Yes, from Simple Ore Generation 3.3 and using an existing world; the IC2 Experimental version has not changed.

**Comment by Rohzek** [comment]
For now, I haven't found an acceptable way to update the ~/configs/simpleoregen/OreGen.json file, so for now you need to back up any changes you've made to it, and then delete it, so that it can be regenerated with the new ore information.

**Comment by sandalle** [comment]
I re-created OreGen.json (I was using the defaults anyways) by deleting configs/simpleoregen/OreGen.json, creating a new world, then deleting the new world, and copying the new configs/simpleoregen/OreGen.json to my current world and starting it up, which worked. :)

**Comment by Rohzek** [comment]
Glad you got it working. :)
