### ISSUE TITLE
Nether/End Lead Ore won't smelt and Surface Lead won't Macerate

### ISSUE THREAD

**Issue by sandalle** [Rohzek/SimpleOreGeneration#5]
After updating to Simple Ore Generation 3.4.0 mc 1.11.2, I disabled the IC2 (experimental) lead ore (and copper) and started finding the Nether Lead Ore (in the Nether ;)) as it should, but I cannot smelt/macerate it, even in a vanilla Furnace.

Just Enough Items says that the Nether Lead Ore (and End Lead Ore) cannot be smelted, only Macerated (I do have B:smeltToIngots=false and B:supportIndustrialCraft=true in configs/simpleoregen/options.cfg), but the Macerator refuses to macerate the ore.

Nether/End Copper and Tin Ore from Simple Ore Generation works fine in the Smelter (vanilla and IC2), but the Surface Copper and Tin Ore from Simple Ore Generation do _not_ work in the Macerator nor Smelter.

The Surface Lead Ore generated by Simple Ore Generation will smelt (vanilla and IC2), but will not macerate. If I spawn in some IC2 or Embers Lead Ore, they will both macerate and smelt.

My configs are available at https://github.com/sandalle/nst-exploration-unofficial if you want to copy them.

Mods:

- Forge Mod Loader 1.11.2-13.20.0.2296
- Simple Ore Generation 3.4.0 mc 1.11.2
- Industrial Craft 2 (Experimental) 2-2.7.12-ex111

**Comment by sandalle** [comment]
Further, the ingots (e.g. Lead Ingots) after smelting the Simple Ore Generation ore isn't usable in crafting (e.g. a Lead Sword from Embers or a Lead Plate from IC2). The recipe shows I can, but once I click to extract the item from a vanilla crafting table, it disappears (nothing is consumed).

**Comment by Rohzek** [comment]
As for the [issue with Lead smelting](https://github.com/Rohzek/SimpleOreGeneration/blob/master/main/java/com/gmail/rohzek/smelting/SmeltingRecipes.java#L86-L106), it was an issue with copying and pasting, and not editing properly. I just needed to change two instances of SURFACE_LEAD_ORE to NETHER_** and END_**

As for the other problems, I was unable to reproduce them. It could be a unique situation to do with your combination of mods. I'll build a pack with the list of mods on the link you provided, and see if I can find it there. In the mean time if you'd like to do further testing, I've uploaded 3.4.1 [here](https://github.com/Rohzek/SimpleOreGeneration/tree/master/build) with the smelting fix.

I'll upload it to CurseForge when your other issues are resolved as well.

**Comment by sandalle** [comment]
https://minecraft.curseforge.com/projects/nst-unofficial-exploration is the modpack on Curse, if you want. It's not up-to-date as it's pending testing and bug fixes such as this one. ;) The GitHub code has the current configs. I'll test 3.4.1 tomorrow, thank you for looking into my bug reports. 👍

**Comment by sandalle** [comment]
Simple Ore Generation 3.4.1 fixes the Lead/Copper/Tin Nether/End ore issues for me on both SSP and SMP, thanks. :)

**Comment by Rohzek** [comment]
Glad this one got taken care of. :)
