### ISSUE TITLE
End Copper Ore is called End Lapis Copper Ore

### ISSUE THREAD

**Issue by sandalle** [Rohzek/SimpleOreGeneration#6]
The Simple Ore Generation (using 3.4.0 and 3.4.1 currently) calls the End version of Copper Ore "End Lapis Copper Ore" instead of "End Copper Ore".

**Comment by Rohzek** [comment]
A quick and easy fix, thanks for pointing that out.
Will be included on the 3.4.1 build that gets uploaded to CurseForge. :)
