### ISSUE TITLE
java.lang.NoClassDefFoundError: ic2/api/recipe/IRecipeInput

### ISSUE THREAD

**Issue by sldmcg** [Rohzek/SimpleOreGeneration#8]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Simple Ore Generation (simpleoregen)
Caused by: java.lang.NoClassDefFoundError: ic2/api/recipe/IRecipeInput

Introduced in 3.4.1

**Comment by Rohzek** [comment]
Assuming you don't have IC2 installed, it seems I forgot to correctly check for if it's installed or not before attempting to add the macerator recipes.

Will fix that right now. :)

**Comment by Rohzek** [comment]
Forgot to close this issue. This was fixed in update 3.4.3
